In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b = np.array([[1.0,2.0,3.0],[6.9,8.0,4.12]])
print(b)

[[1.   2.   3.  ]
 [6.9  8.   4.12]]


In [7]:
b

array([[1.  , 2.  , 3.  ],
       [6.9 , 8.  , 4.12]])

In [9]:
a.shape

(3,)

In [10]:
print(a.shape)

(3,)


In [11]:
b.shape

(2, 3)

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [22]:
a = np.array([1,2,3,4],dtype="int32")

In [23]:
a.dtype

dtype('int32')

In [24]:
a.itemsize

4

In [25]:
a.nbytes

16

In [26]:
a.size

4

In [27]:
a = np.array([[1,2,3,4],[9,80,99,7]])
print(a)

[[ 1  2  3  4]
 [ 9 80 99  7]]


In [28]:
a(1,2)

TypeError: 'numpy.ndarray' object is not callable

In [29]:
a[1,2]

99

In [30]:
a[1,-1]

7

In [31]:
a[0,:]

array([1, 2, 3, 4])

In [32]:
 a[:,0]

array([1, 9])

In [33]:
a[0,:,2]

IndexError: too many indices for array

In [34]:
a[0,1:6:2]

array([2, 4])

In [35]:
 a[0,1:-2:2]

array([2])

In [36]:
a[0,1] = 900

In [37]:
a

array([[  1, 900,   3,   4],
       [  9,  80,  99,   7]])

In [38]:
a[0,:] = 5

In [39]:
a

array([[ 5,  5,  5,  5],
       [ 9, 80, 99,  7]])

In [40]:
a[0,:] = [3,4]

ValueError: cannot copy sequence with size 2 to array axis with dimension 4

In [42]:
a[0,:] = [1,2,99,10008]

In [43]:
a

array([[    1,     2,    99, 10008],
       [    9,    80,    99,     7]])

In [45]:
c= np.zeros

In [46]:
c

<function numpy.zeros>

In [47]:
c  = np.zeros(10)

In [48]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
c = np.zeros(10).reshape(2,5)

In [51]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
c = np.zeros((2,5))

In [53]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
np.ones((2,3,3,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [57]:
np.full((2,3),10,dtype="f")

array([[10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [58]:
np.random((5,10))

TypeError: 'module' object is not callable

In [63]:
np.random.rand((3,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [64]:
np.random.rand(2,5)


array([[0.72272915, 0.49022242, 0.4798505 , 0.23390808, 0.29238835],
       [0.15315781, 0.4321096 , 0.77792557, 0.65173586, 0.87468152]])

In [65]:
a= np.array([[1,2,3,4],[5,6,7,8]])

In [66]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
np.full((2,5),1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
np.full(a.shape,10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [69]:
np.full_like(a,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [70]:
np.random.rand(a.shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [71]:
np.random.random_sample(a.shape)

array([[0.4362981 , 0.58926883, 0.85511719, 0.93709351],
       [0.49634879, 0.57095623, 0.02570668, 0.21659886]])

In [76]:
np.random.randint(10,20)

11

In [77]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
b = np.array([[1,2,3],[4,5,6]])

In [79]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
b.repeat(3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [83]:
m = np.ones((5,5))

In [84]:
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
m[1,:]

array([1., 1., 1., 1., 1.])

In [93]:
m[1,1:4] = 0

In [94]:
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
m[2,1:4] = 0

In [96]:
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
m[3,1:4] = 0

In [98]:
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
m[2,2]=9

In [100]:
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
output = np.ones((5,5))

In [102]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
z = np.zeros((3,3))

In [104]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
z[1,1]=9

In [106]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [107]:
output[1:4,1:4] = z

In [108]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
d = np.array([1,2,3,4])

In [110]:
d

array([1, 2, 3, 4])

In [111]:
d + 2

array([3, 4, 5, 6])

In [112]:
d - 1

array([0, 1, 2, 3])

In [113]:
d ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [114]:
d * 2

array([2, 4, 6, 8])

In [115]:
np.sin(d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [116]:
np.cos(d)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
a = np.ones((2,3))

In [118]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
b = np.full((3,2),4)

In [120]:
b

array([[4, 4],
       [4, 4],
       [4, 4]])

In [121]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [122]:
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [126]:
c = np.identity(3)
print(c)
c = c*2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [127]:
c

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [128]:
np.linalg.det(c)

7.999999999999998

In [129]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
np.min(a,axis=1)

array([1, 4])

In [135]:
np.max(a,axis=1)

array([3, 6])

In [136]:
np.sum(a)

21

In [138]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.vstack([a1,a2,a2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [139]:
np.hstack([a1,a2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [140]:
np.hstack([a2,a1])

array([5, 6, 7, 8, 1, 2, 3, 4])

In [141]:
v1 = np.ones((2,3))
v2 = np.zeros((2,2))
np.hstack([v1,v2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [142]:
a = np.array([1,2,3,4,80,7,33,2,55,64,24,554,5,64,66,3,55,35,35,23])
a

array([  1,   2,   3,   4,  80,   7,  33,   2,  55,  64,  24, 554,   5,
        64,  66,   3,  55,  35,  35,  23])

In [143]:
a > 20

array([False, False, False, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [144]:
a[a>20]

array([ 80,  33,  55,  64,  24, 554,  64,  66,  55,  35,  35,  23])

In [145]:
a

array([  1,   2,   3,   4,  80,   7,  33,   2,  55,  64,  24, 554,   5,
        64,  66,   3,  55,  35,  35,  23])

In [147]:
b = a[[1,3,10]]
b

array([ 2,  4, 24])

In [150]:
(~((a > 20) & (a<100)))

array([ True,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True,  True, False, False,  True, False, False,
       False, False])

In [151]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [153]:
b = a.reshape((6,5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [156]:
b.ndim

2

In [157]:
b[[0,0]]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [158]:
b[[[0,0]]]

C:\Users\naman.agarwal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [159]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [160]:
b[0,0]

1

In [161]:
b[0,:]

array([1, 2, 3, 4, 5])

In [162]:
b[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [163]:
b[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [164]:
b[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [166]:
b[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])